name: users-service

services:
  users-api:
    build: .
    container_name: users-api
    env_file:
      - .env
    ports:
      - "8001:8001"
    volumes:
      - .:/app
    depends_on:
      users-db:
        condition: service_started

  users-db:
    image: postgres:alpine
    env_file:
      - .env
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    ports:
      - "$POSTGRES_PORT:$POSTGRES_PORT"
