name: posts-service

services:
  posts-api:
    build: .
    container_name: posts-api
    env_file:
      - .env
    ports:
      - "8002:8002"
    volumes:
      - .:/app
    depends_on:
      posts-db:
        condition: service_started

  posts-db:
    image: postgres:alpine
    env_file:
      - .env
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    expose:
      - "$POSTGRES_PORT"
    ports:
      - "$POSTGRES_PORT:$POSTGRES_PORT"
    command: -p $POSTGRES_PORT
